use_frameworks!
target 'Drones on Ice Mobile' do
    pod 'Alamofire', '~> 4.0.0'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
  end
